[package]
name = "iso_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.11", features = ['derive'] }
hex = "0.4.3"
tokio = { version = "1.21.2", features=["full"] }
